#!/usr/bin/env python3
"""Generate a minimal static site bundle in generated_sites/.

Usage:
  python3 scripts/generate_site_bundle.py --name my-site --title "My Site"
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from datetime import datetime, timezone


def build_files(title: str) -> dict[str, str]:
    html = f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"UTF-8\" />
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />
  <title>{title}</title>
  <link rel=\"stylesheet\" href=\"style.css\" />
</head>
<body>
  <main>
    <h1>{title}</h1>
    <p>Generated starter site bundle.</p>
    <button id=\"helloBtn\">Say hi</button>
    <p id=\"status\"></p>
  </main>
  <script src=\"script.js\"></script>
</body>
</html>
"""

    css = """body{font-family:Inter,system-ui;margin:0;background:#f6f8fc;color:#16203a}main{max-width:820px;margin:2rem auto;background:#fff;border:1px solid #dbe3f3;border-radius:12px;padding:1rem 1.2rem}button{padding:.6rem .8rem;border-radius:8px;border:1px solid #cfd9ee;background:#eef3ff;cursor:pointer}"""

    js = """document.getElementById('helloBtn')?.addEventListener('click',()=>{const s=document.getElementById('status');if(s)s.textContent='Hello from generated bundle 👋';});"""

    return {"index.html": html, "style.css": css, "script.js": js}


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--name", required=True, help="Bundle folder name")
    parser.add_argument("--title", required=True, help="Page title")
    args = parser.parse_args()

    repo_root = Path(__file__).resolve().parents[1]
    out_dir = repo_root / "generated_sites" / args.name
    out_dir.mkdir(parents=True, exist_ok=True)

    files = build_files(args.title)
    for filename, content in files.items():
        (out_dir / filename).write_text(content, encoding="utf-8")

    metadata = {
        "name": args.name,
        "description": "Generated by scripts/generate_site_bundle.py",
        "style": "starter",
        "pages": ["index"],
        "features": ["starter layout", "status button"],
        "created_at": datetime.now(timezone.utc).isoformat(),
        "files": list(files.keys()),
    }
    (out_dir / "metadata.json").write_text(json.dumps(metadata, indent=2), encoding="utf-8")

    print(f"Generated bundle at: {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
