"""Orchestrator — run a single self-modification cycle end-to-end.

Execution flow (matches ``aria-bot/README.md``):

1. Analyze repository state.
2. Generate improvement plan.
3. Execute safe changes (or simulate, in dry-run).
4. Validate results.
5. Commit changes (only when ``apply`` and ``commit`` are both enabled).

Every cycle writes a machine-readable status file to
``data_out/aria_bot/status.json`` so dashboards and other orchestrators
can observe progress (per the repo's status.json convention).
"""

from __future__ import annotations

import json
import logging
import os
import time
from collections.abc import Sequence
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Protocol, cast

from .analyzer import Analyzer
from .commit_system import CommitSystem
from .defaults import DEFAULT_MAX_PLANS
from .executor import Executor
from .planner import Planner
from .risk_manager import RiskManager
from .validator import Validator

_logger = logging.getLogger(__name__)

# The orchestrator is stateless across runs but always writes its status
# to the same well-known location for observability.
_DEFAULT_STATUS_PATH = Path("data_out") / "aria_bot" / "status.json"

JsonDict = dict[str, Any]


class _ValidationResult(Protocol):  # pylint: disable=too-few-public-methods
    @property
    def ok(self) -> bool:
        """Validation success flag."""
        ...

    def to_dict(self) -> JsonDict:
        """Serialize validation output to a JSON-compatible mapping."""
        ...


class _FindingLike(Protocol):  # pylint: disable=too-few-public-methods
    @property
    def kind(self) -> str:
        """Finding kind identifier."""
        ...

    def to_dict(self) -> JsonDict:
        """Serialize finding output to a JSON-compatible mapping."""
        ...


class _PlanLike(Protocol):  # pylint: disable=too-few-public-methods
    @property
    def path(self) -> Path:
        """Planned target path."""
        ...

    @property
    def kinds(self) -> Sequence[str]:
        """Kinds covered by this plan."""
        ...

    def to_dict(self) -> JsonDict:
        """Serialize plan output to a JSON-compatible mapping."""
        ...


class _ExecutionLike(Protocol):  # pylint: disable=too-few-public-methods
    @property
    def applied(self) -> bool:
        """Whether this execution applied changes."""
        ...

    @property
    def plan(self) -> _PlanLike:
        """Plan executed for this result."""
        ...

    def to_dict(self) -> JsonDict:
        """Serialize execution output to a JSON-compatible mapping."""
        ...


@dataclass
class OrchestratorConfig:
    """User-facing configuration for a single aria-bot cycle.

    Attributes:
        repo_root:   Absolute or relative path to the repository root being
                     processed.
        apply:       When ``False`` (default) the cycle runs in dry-run mode —
                     analysis and planning happen but no files are modified.
        commit:      Whether to commit applied changes via ``CommitSystem``.
                     Ignored when *apply* is ``False``.
        max_plans:   Maximum number of upgrade plans generated by the
                     ``Planner``; guards against runaway sessions.
        status_path: Override for the output ``status.json`` path.  Defaults to
                     ``<repo_root>/data_out/aria_bot/status.json``.
        paths:       Optional subset of paths/directories to analyse.  When
                     ``None`` the analyzer scans the full repository.
    """

    repo_root: Path
    apply: bool = False
    commit: bool = False
    max_plans: int = DEFAULT_MAX_PLANS
    status_path: Path | None = None
    paths: Sequence[Path] | None = None

    def resolve_status_path(self) -> Path:
        """Return the resolved path for the cycle's status.json output file."""
        if self.status_path is not None:
            return Path(self.status_path)
        return Path(self.repo_root) / _DEFAULT_STATUS_PATH


@dataclass
class CycleResult:  # pylint: disable=too-many-instance-attributes
    """Aggregated, JSON-serializable outcome of one aria-bot cycle.

    Produced by ``Orchestrator.run()`` and written to ``status.json``.

    Attributes:
        started_at:       ISO-8601 UTC timestamp when the cycle started.
        finished_at:      ISO-8601 UTC timestamp when the cycle finished.
        duration_seconds: Wall-clock duration of the cycle.
        apply:            Whether the cycle ran in apply mode (mirrors config).
        commit:           Whether a commit was attempted (mirrors config).
        findings:         Raw ``Finding`` objects from the ``Analyzer``.
        plans:            ``UpgradePlan`` objects produced by the ``Planner``.
        executions:       ``ExecutionResult`` objects from the ``Executor``
                          (applied ones have ``applied=True``).
        validation_ok:    ``True`` when post-execution validation passed (or no
                          files were modified).
        validation:       Serialized ``Validator`` result dict.
        commit_sha:       The resulting git commit SHA, or ``None`` when no
                          commit was made.
        notes:            Human-readable log notes appended throughout
                  the cycle.
    """

    started_at: str
    finished_at: str
    duration_seconds: float
    apply: bool
    commit: bool
    findings: Sequence[_FindingLike] = field(default_factory=list)
    plans: Sequence[_PlanLike] = field(default_factory=list)
    executions: Sequence[_ExecutionLike] = field(default_factory=list)
    validation_ok: bool = True
    validation: JsonDict = field(default_factory=dict[str, Any])
    commit_sha: str | None = None
    notes: list[str] = field(default_factory=list[str])

    def _state(
        self,
        applied: Sequence[_ExecutionLike],
        skipped: Sequence[_ExecutionLike],
    ) -> str:
        """Derive a concise state for ``status.json`` ``"state"``."""
        if not self.apply:
            return "dry_run"
        if self.validation_ok is False:
            return "validation_failed"
        if applied:
            return "applied"
        if skipped and not applied:
            return "no_changes"
        return "idle"

    def to_dict(self) -> JsonDict:  # pylint: disable=too-many-locals
        """Serialize the cycle result to a plain dict for ``status.json``.

        The returned dict mirrors the schema consumed by dashboards and CI
        checks: top-level scalar summaries, per-kind breakdowns, path lists,
        and the full findings/plans/executions arrays.
        """
        applied = [e for e in self.executions if e.applied]
        skipped = [e for e in self.executions if not e.applied]
        applied_paths = [str(e.plan.path) for e in applied]
        skipped_paths = [str(e.plan.path) for e in skipped]
        validation_targets = applied_paths if applied_paths else []

        finding_kinds: dict[str, int] = {}
        for finding in self.findings:
            finding_kinds[finding.kind] = finding_kinds.get(finding.kind, 0) + 1

        plan_kinds: dict[str, int] = {}
        for plan in self.plans:
            for kind in plan.kinds:
                plan_kinds[kind] = plan_kinds.get(kind, 0) + 1

        def _format_kind_summary(kind_counts: dict[str, int]) -> str:
            if not kind_counts:
                return "none"
            return ", ".join(f"{kind}={count}" for kind, count in sorted(kind_counts.items()))

        counts = {
            "findings": len(self.findings),
            "plans": len(self.plans),
            "executions": len(self.executions),
            "applied": len(applied),
            "skipped": len(skipped),
        }

        state = self._state(applied, skipped)
        status_text = (
            f"{state}: {counts['findings']} finding(s), "
            f"{counts['plans']} plan(s), "
            f"{counts['applied']} applied, {counts['skipped']} skipped"
        )

        summary = {
            "state": state,
            "status_text": status_text,
            "counts": counts,
            "paths": {
                "applied": applied_paths,
                "skipped": skipped_paths,
                "validated": validation_targets,
            },
            "by_kind": {
                "findings": finding_kinds,
                "plans": plan_kinds,
            },
            "kind_summary": {
                "findings": _format_kind_summary(finding_kinds),
                "plans": _format_kind_summary(plan_kinds),
            },
        }

        return {
            "started_at": self.started_at,
            "finished_at": self.finished_at,
            "duration_seconds": round(self.duration_seconds, 3),
            "apply": self.apply,
            "commit": self.commit,
            "totals": {
                "findings": len(self.findings),
                "plans": len(self.plans),
                "executions": len(self.executions),
                "applied": len(applied),
                "skipped": len(skipped),
            },
            "findings": [f.to_dict() for f in self.findings],
            "plans": [p.to_dict() for p in self.plans],
            "executions": [e.to_dict() for e in self.executions],
            "status_text": status_text,
            "applied_paths": applied_paths,
            "skipped_paths": skipped_paths,
            "validation_targets": validation_targets,
            "summary": summary,
            "validation_ok": self.validation_ok,
            "validation": dict(self.validation),
            "commit_sha": self.commit_sha,
            "notes": list(self.notes),
        }


@dataclass
class Orchestrator:
    """Wire the aria-bot modules together for a single self-modification cycle.

    Instantiate with an ``OrchestratorConfig`` and call ``run()`` once; the
    object carries no mutable state between cycles so a fresh instance should
    be created for each run.
    """

    config: OrchestratorConfig

    # pylint: disable=too-many-locals
    def run(self) -> CycleResult:
        """Execute one full cycle: analyse → plan → execute → validate → (commit).

        Writes a ``status.json`` to ``config.resolve_status_path()``
        regardless of outcome so dashboards always have fresh data.

        Returns:
            A ``CycleResult`` containing findings, plans, execution outcomes,
            validation status, and an optional commit SHA.
        """
        started = time.monotonic()
        started_iso = datetime.now(timezone.utc).isoformat()

        repo_root = Path(self.config.repo_root).resolve()
        risk = RiskManager(repo_root=repo_root)
        analyzer = Analyzer(risk_manager=risk)
        planner = Planner(
            risk_manager=risk,
            max_plans=self.config.max_plans,
        )
        executor = Executor(
            risk_manager=risk,
            dry_run=not self.config.apply,
        )
        validator = Validator(repo_root=repo_root)
        commits = CommitSystem(repo_root=repo_root)

        notes: list[str] = []

        _logger.info("aria-bot: scanning repository at %s", repo_root)
        scan_paths = self._resolve_paths(analyzer) if self.config.paths else None
        findings = cast(
            list[_FindingLike],
            list(analyzer.scan(paths=scan_paths)),
        )
        _logger.info("aria-bot: %d finding(s)", len(findings))

        plans = cast(
            list[_PlanLike],
            list(planner.build_plans(cast(Any, findings))),
        )
        _logger.info("aria-bot: %d plan(s) after risk filter", len(plans))

        executions = cast(
            list[_ExecutionLike],
            list(executor.execute(cast(Any, plans))),
        )
        applied_paths = [e.plan.path for e in executions if e.applied]
        skipped_paths = [e.plan.path for e in executions if not e.applied]

        # Only validate when files were actually modified — dry-runs and
        # no-op cycles have nothing to validate.
        validation: _ValidationResult
        if applied_paths:
            validation = cast(
                _ValidationResult,
                validator.validate(applied_paths),
            )
        else:
            validation = cast(
                _ValidationResult,
                validator.validate(changed_paths=[]),
            )
        notes.append(
            f"execution summary: {len(executions)} plan(s), {len(applied_paths)} applied, {len(skipped_paths)} skipped"
        )
        if not validation.ok:
            notes.append("validation failed; skipping commit")
        elif applied_paths:
            notes.append(f"validated {len(applied_paths)} applied path(s)")

        commit_sha: str | None = None
        if self.config.apply and self.config.commit and validation.ok and applied_paths:
            message = self._commit_message(executions)
            commit_sha = commits.commit(applied_paths, message)
            if commit_sha is None:
                notes.append("commit step produced no SHA (nothing staged or git unavailable)")
        elif not self.config.apply:
            notes.append("dry-run: no files were modified")
        elif not applied_paths:
            notes.append("no plans were applied")

        finished = time.monotonic()
        finished_iso = datetime.now(timezone.utc).isoformat()
        result = CycleResult(
            started_at=started_iso,
            finished_at=finished_iso,
            duration_seconds=finished - started,
            apply=self.config.apply,
            commit=self.config.commit,
            findings=findings,
            plans=plans,
            executions=executions,
            validation_ok=validation.ok,
            validation=validation.to_dict(),
            commit_sha=commit_sha,
            notes=notes,
        )
        self._write_status(result)
        return result

    # ------------------------------------------------------------------
    def _resolve_paths(self, analyzer: Analyzer) -> list[Path]:
        """Expand ``config.paths`` into files understood by the analyzer."""
        repo_root = Path(self.config.repo_root).resolve()
        result: list[Path] = []
        wanted = {s.lower() for s in analyzer.suffixes}
        for p in self.config.paths or []:
            p = Path(p)
            if not p.is_absolute():
                p = repo_root / p
            if p.is_dir():
                for root, _, files in os.walk(p):
                    for name in files:
                        fp = Path(root, name)
                        if fp.suffix.lower() in wanted:
                            result.append(fp)
            elif p.is_file():
                result.append(p)
            else:
                _logger.debug("--paths target does not exist: %s", p)
        return result

    def _commit_message(self, executions: Sequence[_ExecutionLike]) -> str:
        # Only called when at least one execution applied; defend against
        # accidental misuse by future callers.
        applied = [e for e in executions if e.applied]
        if not applied:
            return "no applied changes"
        kinds: set[str] = set()
        for e in applied:
            kinds.update(e.plan.kinds)
        kind_str = ",".join(sorted(kinds))
        return f"apply {kind_str} to {len(applied)} file(s)"

    def _write_status(self, result: CycleResult) -> None:
        status_path = self.config.resolve_status_path()
        try:
            status_path.parent.mkdir(parents=True, exist_ok=True)
            status_path.write_text(
                json.dumps(result.to_dict(), indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
        except OSError as exc:  # pragma: no cover - filesystem dependent
            _logger.warning(
                "unable to write status file %s: %s",
                status_path,
                exc,
            )


# pylint: disable=too-many-arguments
def run_cycle(
    repo_root: Path,
    *,
    apply: bool = False,
    commit: bool = False,
    max_plans: int = DEFAULT_MAX_PLANS,
    status_path: Path | None = None,
    paths: Sequence[Path] | None = None,
) -> CycleResult:
    """Build an ``OrchestratorConfig`` and run one cycle.

    Preferred over constructing ``Orchestrator`` directly in the CLI and tests.

    Args:
        repo_root:   Path to the repository root.
        apply:       Execute changes (``False`` = dry-run).
        commit:      Commit applied changes; ignored when *apply* is ``False``.
        max_plans:   Cap on the number of plans generated per cycle.
        status_path: Optional override for the output ``status.json`` path.
        paths:       Restrict analysis to these paths/directories.

    Returns:
        The ``CycleResult`` for the completed cycle.
    """

    config = OrchestratorConfig(
        repo_root=Path(repo_root),
        apply=apply,
        commit=commit,
        max_plans=max_plans,
        status_path=status_path,
        paths=list(paths) if paths else None,
    )
    return Orchestrator(config=config).run()
